"""
analyze_synthetic_crosstask_blocked.py — Cross-task α-transfer test.

Task 1 (training task, already done):
    data_dataset{ID}: 200-trial 2-arm bandit with reversals (interval=50).
    Each session i has a true α_i. IDRNN was trained → per-session latent z_i;
    Vanilla RNN was trained → per-session last hidden state h_i.

Task 2 (held-out, generated here — models never see it):
    20 blocks × 10 trials, Bernoulli arms p_high ∈ U(0.70, 0.85) and
    p_low ∈ U(0.15, 0.30), independently per block. Q-learner resets Q to 0
    at every block boundary. ONE shared env schedule across all participants
    (so Pearson r reflects α-driven variance only).

Target (per session):
    Q-truth mean regret on task 2, generated by an FQ Q-learner with that
    session's true (α_P, α_N, α_F, β) from true_parameter_values.csv. Averaged
    over n_qsim_seeds independent choice-sampling seeds to remove sampling
    noise. Regret_t = max(reward arm) − received reward.

Predictors (loaded from plots_dataset{ID}/step1_three_regressions.npz):
    R1 — exact-env task-1 rollout regret (npz keys R2_*)
    R2 — marg-env task-1 rollout regret  (npz keys R3_*)
    for each of IDRNN, Vanilla+h, Vanilla.

Output:
    plots_dataset{ID}/crosstask_blocked.{npz,png}

Usage: python analyze_synthetic_crosstask_blocked.py --dataset_id 0
"""
import os, argparse
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from scipy import stats
from pingouin import bayesfactor_pearson


# ── Held-out task generator ────────────────────────────────────────────────
N_BLOCKS  = 20
BLOCK_LEN = 10
BETA      = 3.0     # matches generate_parameter_lists default for uniform ind-diff
P_HIGH    = (0.70, 0.85)
P_LOW     = (0.15, 0.30)


def gen_blocked_bernoulli_env(seed, n_blocks=N_BLOCKS, block_len=BLOCK_LEN):
    """One shared env: (n_blocks, block_len, 2) Bernoulli rewards.
    Better-arm side is randomised per block."""
    rng = np.random.default_rng(seed)
    rewards = np.zeros((n_blocks, block_len, 2), dtype=np.float32)
    true_p  = np.zeros((n_blocks, 2),            dtype=np.float32)
    for b in range(n_blocks):
        p_h = rng.uniform(*P_HIGH)
        p_l = rng.uniform(*P_LOW)
        if rng.random() < 0.5:
            p_arm = (p_h, p_l)
        else:
            p_arm = (p_l, p_h)
        true_p[b] = p_arm
        u = rng.random((block_len, 2))
        rewards[b, :, 0] = (u[:, 0] < p_arm[0]).astype(np.float32)
        rewards[b, :, 1] = (u[:, 1] < p_arm[1]).astype(np.float32)
    return rewards, true_p


# ── FQ Q-learning on the blocked task (matches sim_Q_data.simulate_Qlearning) ──
def q_truth_regret(env, alphaP, alphaN, alphaF, beta, n_seeds, base_seed):
    """env: (n_blocks, block_len, 2). Returns mean per-trial regret over
    n_seeds independent choice-sampling rollouts. Q resets per block."""
    n_blocks, block_len, _ = env.shape
    total = 0.0
    for k in range(n_seeds):
        rng = np.random.default_rng(base_seed + k)
        for b in range(n_blocks):
            Q = np.zeros(2)
            for t in range(block_len):
                v = np.array([beta * Q[0], beta * Q[1]])
                v = v - v.max()
                p = np.exp(v); p /= p.sum()
                c = 0 if rng.random() < p[0] else 1
                r = float(env[b, t, c])
                rmax = float(env[b, t].max())
                total += (rmax - r)
                if t < block_len - 1:
                    delta = r - Q[c]
                    Q_new = (1.0 - alphaF) * Q
                    Q_new[c] = Q[c] + (alphaP if delta > 0 else alphaN) * delta
                    Q = Q_new
    return total / (n_seeds * n_blocks * block_len)


# ── Stats: Pearson r + bootstrap CI + BF ──────────────────────────────────
def r_ci_bf(x, y, n_boot=2000, seed=0):
    m = np.isfinite(x) & np.isfinite(y)
    xv, yv = x[m], y[m]
    if len(xv) < 5:
        return np.nan, (np.nan, np.nan), 0, np.nan, np.full(n_boot, np.nan)
    r0 = float(stats.pearsonr(xv, yv)[0])
    rng = np.random.default_rng(seed)
    n = len(xv)
    boots = np.empty(n_boot)
    for i in range(n_boot):
        idx = rng.integers(0, n, size=n)
        a, b = xv[idx], yv[idx]
        boots[i] = np.corrcoef(a, b)[0, 1] if a.std() and b.std() else np.nan
    lo, hi = np.nanpercentile(boots, [2.5, 97.5])
    bf = float(bayesfactor_pearson(r0, n))
    return r0, (float(lo), float(hi)), n, bf, boots


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dataset_id", type=int, default=0)
    ap.add_argument("--env_seed",   type=int, default=2026)
    ap.add_argument("--n_qsim_seeds", type=int, default=200,
                    help="Choice-sampling seeds per session for Q-truth target.")
    args = ap.parse_args()

    DATA_DIR = f"data_dataset{args.dataset_id}"
    PLOT_DIR = f"plots_dataset{args.dataset_id}"
    os.makedirs(PLOT_DIR, exist_ok=True)

    # ── Load task-1 rollout predictors ───────────────────────────────────────
    npz_path = os.path.join(PLOT_DIR, "step1_three_regressions.npz")
    npz = np.load(npz_path)
    print(f"Loaded predictors from {npz_path}")
    PREDICTORS = [
        # (display name,    env condition,        npz key)
        ("IDRNN",           "R1 (exact env task 1)", "R2_idrnn"),
        ("IDRNN",           "R2 (marg env task 1)",  "R3_idrnn"),
        ("Vanilla+h",       "R1 (exact env task 1)", "R2_vanH"),
        ("Vanilla+h",       "R2 (marg env task 1)",  "R3_vanH"),
        ("Vanilla",         "R1 (exact env task 1)", "R2_van0"),
        ("Vanilla",         "R2 (marg env task 1)",  "R3_van0"),
    ]
    preds = {key: np.asarray(npz[key]) for _, _, key in PREDICTORS}
    n_sessions = len(npz["true_alpha"])
    print(f"  n_sessions = {n_sessions}")

    # ── Load per-session true Q-learner params ──────────────────────────────
    true_df = pd.read_csv(f"{DATA_DIR}/true_parameter_values.csv")
    alphaP = true_df["alphaP_list"].values.astype(float)
    alphaN = true_df["alphaN_list"].values.astype(float)
    alphaF = true_df["alphaF_list"].values.astype(float)
    if "beta_list" in true_df.columns:
        beta_col = true_df["beta_list"].values.astype(float)
    else:
        beta_col = np.full(n_sessions, BETA)
    print(f"  α_P range [{alphaP.min():.2f}, {alphaP.max():.2f}], "
          f"β range [{beta_col.min():.2f}, {beta_col.max():.2f}]")
    assert len(alphaP) == n_sessions, \
        f"param csv has {len(alphaP)} rows but npz has {n_sessions} sessions"

    # ── Generate held-out task 2 (shared across sessions) ───────────────────
    env, true_p = gen_blocked_bernoulli_env(seed=args.env_seed)
    print(f"\nHeld-out task 2: {N_BLOCKS} blocks × {BLOCK_LEN} trials "
          f"(env_seed={args.env_seed})")
    print(f"  arm-mean reward over all blocks: arm0={env[..., 0].mean():.3f}, "
          f"arm1={env[..., 1].mean():.3f}")
    print(f"  per-block max-arm p̂ (mean): {true_p.max(axis=1).mean():.3f}")

    # ── Q-truth target: mean regret per session on task 2 ───────────────────
    print(f"\nRunning Q-truth on task 2 ({args.n_qsim_seeds} seeds/session) ...")
    q_truth = np.full(n_sessions, np.nan)
    for s in range(n_sessions):
        q_truth[s] = q_truth_regret(env, alphaP[s], alphaN[s], alphaF[s],
                                    beta_col[s], args.n_qsim_seeds,
                                    base_seed=7919 * s + 11)
        if (s + 1) % 25 == 0:
            print(f"  {s+1}/{n_sessions} sessions done")
    print(f"  Q-truth regret: mean={q_truth.mean():.3f}, sd={q_truth.std():.3f}")

    # Sanity: Q-truth regret should correlate with α (faster learner → lower regret)
    r_truth_alpha = float(np.corrcoef(q_truth, alphaP)[0, 1])
    bf_truth_alpha = float(bayesfactor_pearson(r_truth_alpha, n_sessions))
    print(f"  sanity: r(Q-truth regret, α) = {r_truth_alpha:+.3f}, "
          f"BF₁₀={bf_truth_alpha:.2g}")

    # ── Correlate each predictor with Q-truth target ────────────────────────
    print("\nResults (predictor → Q-truth task-2 regret):")
    print(f"{'predictor':<35}{'n':>4}   {'r [CI]':<22}{'BF₁₀':>10}")
    results = []
    for model, cond, key in PREDICTORS:
        r, ci, n, bf, boots = r_ci_bf(preds[key], q_truth, seed=1)
        results.append(dict(model=model, cond=cond, key=key,
                            r=r, ci=ci, n=n, bf=bf, boots=boots))
        print(f"{f'{model} {cond}':<35}{n:>4}   "
              f"{r:+.3f} [{ci[0]:+.2f}, {ci[1]:+.2f}]   {bf:>10.2g}")

    # ── Save ────────────────────────────────────────────────────────────────
    out_npz = os.path.join(PLOT_DIR, "crosstask_blocked.npz")
    save = dict(
        q_truth_regret=q_truth, true_alpha=alphaP, env_rewards=env,
        env_true_p=true_p, env_seed=np.array([args.env_seed]),
        r_truth_alpha=np.array([r_truth_alpha]),
        bf_truth_alpha=np.array([bf_truth_alpha]),
    )
    for key in preds:
        save[f"pred_{key}"] = preds[key]
    np.savez(out_npz, **save)
    print(f"\nSaved arrays → {out_npz}")

    # ── Plot: bar chart of r values (panel-e style) ─────────────────────────
    COL_IDRNN   = "#2a82c2"
    COL_VAN_H   = "#8C564B"
    COL_VANILLA = "#e1861f"
    COLORS = {"IDRNN": COL_IDRNN, "Vanilla+h": COL_VAN_H, "Vanilla": COL_VANILLA}
    # R1 (exact) faded, R2 (marg) full
    ALPHA_BY_COND = {"R1 (exact env task 1)": 0.45,
                     "R2 (marg env task 1)":  1.00}

    fig, ax = plt.subplots(figsize=(8.5, 5.0))
    xs = np.arange(len(results))
    heights = [r["r"] for r in results]
    lo_err  = [abs(r["r"] - r["ci"][0]) for r in results]
    hi_err  = [abs(r["ci"][1] - r["r"]) for r in results]
    for xi, rec in zip(xs, results):
        ax.bar(xi, rec["r"], color=COLORS[rec["model"]],
               alpha=ALPHA_BY_COND[rec["cond"]],
               edgecolor="black", linewidth=0.5, zorder=2)

    # Bootstrap dot cloud
    rng_pts = np.random.default_rng(7)
    for xi, rec in zip(xs, results):
        if np.all(np.isnan(rec["boots"])): continue
        sample = rng_pts.choice(rec["boots"], size=80, replace=False)
        j = rng_pts.normal(0, 0.045, size=80)
        ax.scatter(xi + j, sample, s=5, c="black", alpha=0.40,
                   edgecolors="none", zorder=4)

    ax.errorbar(xs, heights, yerr=[lo_err, hi_err], fmt="none",
                ecolor="#888888", elinewidth=0.7, capsize=0, zorder=5)

    # BF labels above each bar
    for xi, rec in zip(xs, results):
        bf_str = (f"{rec['bf']:.2g}" if rec["bf"] >= 100
                  else f"{rec['bf']:.2f}")
        y = rec["r"] + hi_err[xi] + 0.020 if rec["r"] >= 0 \
            else rec["r"] - lo_err[xi] - 0.030
        va = "bottom" if rec["r"] >= 0 else "top"
        ax.text(xi, y, bf_str, ha="center", va=va, fontsize=8)

    ax.axhline(0, color="grey", lw=0.7, ls=":")
    ax.set_xticks(xs)
    ax.set_xticklabels([f"{r['model']}\n{'exact' if 'exact' in r['cond'] else 'marg'}"
                        for r in results], fontsize=9)
    ax.set_ylabel("Pearson r (task-1 rollout regret → Q-truth task-2 regret)")
    ax.set_title(
        f"Cross-task α-transfer (dataset {args.dataset_id}, n={n_sessions})\n"
        f"sanity r(Q-truth task-2 regret, α) = {r_truth_alpha:+.3f}, "
        f"BF₁₀={bf_truth_alpha:.2g}",
        fontsize=10)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)

    out_png = os.path.join(PLOT_DIR, "crosstask_blocked.png")
    fig.tight_layout()
    fig.savefig(out_png, dpi=200, bbox_inches="tight")
    print(f"Saved figure → {out_png}")
    print("\nDone.")


if __name__ == "__main__":
    main()
