_wandb:
    value:
        cli_version: 0.23.1
        e:
            62qotstnoi2kbkflhek961gn8lg4h42r:
                args:
                    - --lmbd
                    - "0.5"
                    - --z
                    - "3"
                    - --seed
                    - "76"
                codePath: run_Q_model.py
                codePathLocal: run_Q_model.py
                cpu_count: 112
                cpu_count_logical: 224
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "321965260800"
                        used: "50785054720"
                email: marvin.mathony@gmail.com
                executable: /ictstr01/home/hcai/marvin.mathony/tools/apps/mamba/envs/RNNproject/bin/python
                git:
                    commit: cd8a84c7492a2dd47d952e58045dbacdee9a4c36
                    remote: https://marvinmathony:@github.com/marvinmathony/ClusterRNNIndDiffs.git
                gpu: NVIDIA H100 80GB HBM3
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-b6b01399-23d7-fefd-7fd4-10e5bc3637f8
                host: supergpu29.scidom.de
                memory:
                    total: "2163576700928"
                os: Linux-5.14.0-570.25.1.el9_6.x86_64-x86_64-with-glibc2.34
                program: /ictstr01/home/hcai/marvin.mathony/RNNsandUncertainty/run_Q_model.py
                python: CPython 3.9.19
                root: /ictstr01/home/hcai/marvin.mathony/RNNsandUncertainty
                slurm:
                    cluster_name: algoritam
                    conf: /etc/slurm/slurm.conf
                    cpus_on_node: "20"
                    cpus_per_task: "20"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: aih
                    job_cpus_per_node: "20"
                    job_end_time: "1767945859"
                    job_gid: "20309"
                    job_gpus: "7"
                    job_id: "33132346"
                    job_name: GRU4
                    job_nodelist: supergpu29
                    job_num_nodes: "1"
                    job_partition: gpu_p
                    job_qos: gpu_normal
                    job_start_time: "1767888259"
                    job_uid: "1000263"
                    job_user: marvin.mathony
                    jobid: "33132346"
                    launch_node_ipaddr: 10.233.0.251
                    localid: "0"
                    mem_per_node: "32768"
                    mpi_type: none
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: supergpu29
                    oom_kill_step: "0"
                    open_mode: a
                    prio_process: "0"
                    procid: "0"
                    pty_port: "61101"
                    pty_win_col: "210"
                    pty_win_row: "21"
                    srun_comm_host: 10.233.0.251
                    srun_comm_port: "60886"
                    step_id: "4294967290"
                    step_launcher_port: "60886"
                    step_nodelist: supergpu22
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_tasks_per_node: "1"
                    stepid: "4294967290"
                    submit_dir: /ictstr01/home/hcai/marvin.mathony/RNNsandUncertainty
                    submit_host: supergpu22.scidom.de
                    task_pid: "2966272"
                    tasks_per_node: "1"
                    topology_addr: supergpu29
                    topology_addr_pattern: node
                    tres_per_task: cpu=20
                startedAt: "2026-01-08T17:09:00.430053Z"
                writerId: 62qotstnoi2kbkflhek961gn8lg4h42r
        m: []
        python_version: 3.9.19
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 53
            "2":
                - 1
                - 2
                - 3
                - 5
                - 53
            "3":
                - 2
                - 16
                - 61
            "4": 3.9.19
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
latent:
    value: false
lmbd:
    value: 0.5
seed:
    value: 76
z:
    value: 3
